{
  try {
    getChecked(FAILED_FUTURE_CHECKED_EXCEPTION,1,TimeUnit.SECONDS,ExceptionWithGoodAndBadConstructor.class);
    fail();
  }
 catch (  ExceptionWithGoodAndBadConstructor expected) {
    assertSame(CHECKED_EXCEPTION,expected.getCause());
  }
}
