{
  SomeError cause=new SomeError();
  SomeChainingException outer=new SomeChainingException(cause);
  StackTraceElement[] expectedTrace=ObjectArrays.concat(cause.getStackTrace(),outer.getStackTrace(),StackTraceElement.class);
  try {
    Throwables.throwCause(outer,true);
    fail("Exception not thrown properly");
  }
 catch (  Error e) {
    assertSame(e,cause);
    assertTrue(Arrays.equals(expectedTrace,e.getStackTrace()));
  }
}
