{
  try {
    set(task.call());
  }
 catch (  ExecutionException e) {
    setException(e.getCause());
  }
catch (  CancellationException e) {
    cancel(false);
  }
}
