{
  final RuntimeException raisedException=new RuntimeException();
  AsyncFunctionSpy<Throwable,Integer> fallback=spy(new AsyncFunction<Throwable,Integer>(){
    @Override public ListenableFuture<Integer> apply(    Throwable t) throws Exception {
      assertThat(t).isSameAs(raisedException);
      return immediateFuture(20);
    }
  }
);
  ListenableFuture<Integer> failingFuture=immediateFailedFuture(raisedException);
  ListenableFuture<Integer> faultTolerantFuture=catchingAsync(failingFuture,Throwable.class,fallback);
  assertEquals(20,getDone(faultTolerantFuture).intValue());
  fallback.verifyCallCount(1);
}
