{
  try {
    getDone(allAsList(immediateFailedFuture(new MyError())));
    fail();
  }
 catch (  ExecutionException expected) {
    assertThat(expected.getCause()).isInstanceOf(MyError.class);
    List<LogRecord> logged=aggregateFutureLogHandler.getStoredLogRecords();
    assertThat(logged).hasSize(1);
    assertThat(logged.get(0).getThrown()).isInstanceOf(MyError.class);
  }
}
