{
  try {
    getChecked(FAILED_FUTURE_ERROR,TwoArgConstructorException.class,0,SECONDS);
    fail();
  }
 catch (  ExecutionError expected) {
    assertEquals(ERROR,expected.getCause());
  }
}
